version: '3'

services:
  fincheck-db:
    container_name: fincheck-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - fincheck_data:/var/lib/postgresql/data
    
volumes:
  fincheck_data: